version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: ryo_postgres
    environment:
      POSTGRES_DB: ${PSQL_NAME:-ryo_db}
      POSTGRES_USER: ${PSQL_USER:-postgres}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD:-postgres}
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ryo-network
    restart: unless-stopped

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ryo_backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/media:/app/media
      # - static_volume:/app/staticfiles  # Mount static files volume
      - ./staticfiles:/app/staticfiles  # Mount for WSL Nginx access
    ports:
      - "8081:8080"  # Map host port 8081 to container port 8080
    networks:
      - ryo-network
    depends_on:
      - db
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: ryo_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - ryo-network

volumes:
  postgres_data:


networks:
  ryo-network:
    driver: bridge