version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: ryo_postgres
    environment:
      POSTGRES_DB: ${PSQL_NAME:-ryo_db}
      POSTGRES_USER: ${PSQL_USER:-postgres}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD:-postgres}
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ryo-network
    restart: unless-stopped

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ryo_backend
    env_file:
      - .env
    volumes:
      - ./backend/media:/app/media
      - static_volume:/app/staticfiles  # Mount static files volume
      - ./staticfiles:/app/staticfiles-host  # Mount for WSL Nginx access
    ports:
      - "8082:8080"  # Map host port 8082 to container port 8080 (matches .env API_BASE_URL)
    networks:
      - ryo-network
    depends_on:
      - db
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: ryo_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8082/api  # Updated to match backend port
    ports:
      - "8080:80"  # Frontend on port 8080 (matches .env FRONTEND_URL)
    restart: unless-stopped
    networks:
      - ryo-network

volumes:
  static_volume:
  postgres_data:


networks:
  ryo-network:
    driver: bridge
