version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: ryo_postgres
    environment:
      POSTGRES_DB: ${PSQL_NAME:-ryo_db}
      POSTGRES_USER: ${PSQL_USER:-postgres}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD:-postgres}
    ports:
      - "127.0.0.1:5433:5432"  # PostgreSQL for ALB target group port 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ryo-network
    restart: unless-stopped
    
  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ryo_backend
    env_file:
      - .env
    volumes:
      - ./backend/media:/app/media
      - static_volume:/app/staticfiles
      - ./staticfiles:/app/staticfiles-host
    ports:
      - "127.0.0.1:8082:8080"  # Backend for ALB target group port 8082
    networks:
      - ryo-network
    depends_on:
      - db
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: ryo_frontend
    ports:
      - "127.0.0.1:8080:80"  # Frontend for ALB target group port 8080
    networks:
      - ryo-network
    restart: unless-stopped

volumes:
  static_volume:
  postgres_data:

networks:
  ryo-network:
    driver: bridge